services:

  epc:
    build:
      context: .
    container_name: lte-epc

    command: >
      srsepc
      /etc/srsran/epc.conf
      --mme.mme_bind_addr=10.10.10.10
      --spgw.gtpu_bind_addr=10.10.10.10

    cap_add:
      - NET_ADMIN
      - SYS_NICE

    devices:
      - /dev/net/tun:/dev/net/tun

    networks:
      lte-net:
        ipv4_address: 10.10.10.10


  tower:
    build:
      context: .
    container_name: lte-tower

    privileged: true

    depends_on:
      - epc

    command: >
      srsenb
      /etc/srsran/enb.conf
      --enb.mme_addr=10.10.10.10
      --enb.gtp_bind_addr=10.10.10.20
      --enb.s1c_bind_addr=10.10.10.20
      --rf.device_name=zmq
      --rf.device_args=fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://client:2001,id=enb,base_srate=23.04e6

    cap_add:
      - SYS_NICE

    ulimits:
      rtprio:
        soft: 99
        hard: 99

    networks:
      lte-net:
        ipv4_address: 10.10.10.20


  client:
    build:
      context: .
    container_name: lte-client

    privileged: true

    depends_on:
      - tower

    command: >
      srsue
      /etc/srsran/ue.conf
      --rf.device_name=zmq
      --rf.device_args=tx_port=tcp://*:2001,rx_port=tcp://tower:2000,id=ue,base_srate=23.04e6

    cap_add:
      - NET_ADMIN
      - SYS_NICE

    ulimits:
      rtprio:
        soft: 99
        hard: 99

    devices:
      - /dev/net/tun:/dev/net/tun

    networks:
      lte-net:


networks:

  lte-net:
    driver: bridge

    ipam:
      config:
        - subnet: 10.10.10.0/24